default: &default
  adapter: postgresql
  encoding: unicode
  <% if ENV['POSTGRESQL_CONTAINER'].present? %>
  host: db
  username: postgres
  password: password
  <% end %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ServiceLinkApi_development

test:
  <<: *default
  database: ServiceLinkApi_test

production:
  <<: *default
  database: ServiceLinkApi_production
  username: ServiceLinkApi
  password: <%= ENV["SERVICELINKAPI_DATABASE_PASSWORD"] %>
